In [1]:
import pandas as pd

df = pd.read_csv("tech_jobs_salaries.csv")

df.head()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   job_title               200000 non-null  object
 1   company_size            200000 non-null  object
 2   employment_type         200000 non-null  object
 3   experience_level        200000 non-null  object
 4   years_experience        200000 non-null  int64
 5   education_level         200000 non-null  object
 6   country                 200000 non-null  object
 7   salary_local_currency   200000 non-null  int64
 8   currency                200000 non-null  object
 9   remote_type             200000 non-null  object
 10  primary_skill           200000 non-null  object
 11  secondary_skill         200000 non-null  object
 12  work_hours_per_week     200000 non-null  int64
 13  job_satisfaction_score  200000 non-null  float64
 14  company_rating          200000 non-null  float64
 15  age                     200000 non-null  int64
 16  gender                  200000 non-null  object
dtypes: float64(2), int64(4), object(11)
memory usage: 25.9+ MB

In [2]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")
df.columns

Index(['job_title', 'company_size', 'employment_type', 'experience_level',
       'years_experience', 'education_level', 'country',
       'salary_local_currency', 'currency', 'remote_type', 'primary_skill',
       'secondary_skill', 'work_hours_per_week', 'job_satisfaction_score',
       'company_rating', 'age', 'gender'],
      dtype='object')

In [3]:
df.isnull()

,job_title,company_size,employment_type,experience_level,years_experience,education_level,country,salary_local_currency,currency,remote_type,primary_skill,secondary_skill,work_hours_per_week,job_satisfaction_score,company_rating,age,gender
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
199996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
199997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
199998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
199999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
df.isnull().sum()

job_title                 0
company_size              0
employment_type           0
experience_level          0
years_experience          0
education_level           0
country                   0
salary_local_currency     0
currency                  0
remote_type               0
primary_skill             0
secondary_skill           0
work_hours_per_week       0
job_satisfaction_score    0
company_rating            0
age                       0
gender                    0
dtype: int64

In [5]:
df.duplicated().sum()

df = df.drop_duplicates()

In [6]:
df['salary'] = pd.to_numeric(df['salary_local_currency'], errors='coerce')

In [7]:
df.head()

,job_title,company_size,employment_type,experience_level,years_experience,education_level,country,salary_local_currency,currency,remote_type,primary_skill,secondary_skill,work_hours_per_week,job_satisfaction_score,company_rating,age,gender,salary
0,DevOps Engineer,SME,Full-time,Entry,3,Self-taught,India,1087489,INR,Onsite,SQL,Java,35,2.7,3.3,22,Female,1087489
1,Blockchain Engineer,Mid-size,Full-time,Lead,5,Diploma,France,133007,USD,Hybrid,AWS,React,41,4.9,3.5,26,Prefer not to say,133007
2,Cloud Engineer,Startup,Freelance,Senior,14,Self-taught,India,2579715,INR,Onsite,Kubernetes,C++,52,3.2,4.2,44,Female,2579715
3,Cybersecurity Analyst,Startup,Full-time,Entry,3,Diploma,India,949111,INR,Hybrid,NoSQL,Docker,40,3.4,3.3,38,Male,949111
4,DevOps Engineer,SME,Contract,Mid,12,PhD,Japan,13961380,USD,Remote,PyTorch,GCP,59,4.4,3.3,23,Other,13961380

In [8]:
df.describe(include='all')

,job_title,company_size,employment_type,experience_level,years_experience,education_level,country,salary_local_currency,currency,remote_type,primary_skill,secondary_skill,work_hours_per_week,job_satisfaction_score,company_rating,age,gender,salary
count,200000,200000,200000,200000,200000.000000,200000,200000,2.000000e+05,200000,200000,200000,200000,200000.000000,200000.000000,200000.000000,200000.000000,200000,2.000000e+05
unique,16,4,3,4,NaN,5,10,NaN,2,3,16,16,NaN,NaN,NaN,NaN,4,NaN
top,Blockchain Engineer,Mid-size,Contract,Senior,NaN,Diploma,France,NaN,USD,Hybrid,Docker,Kubernetes,NaN,NaN,NaN,NaN,Male,NaN
freq,12692,50317,66780,50456,NaN,40106,20171,NaN,179997,66807,12629,12821,NaN,NaN,NaN,NaN,50266,NaN
mean,NaN,NaN,NaN,NaN,9.996435,NaN,NaN,1.482697e+06,NaN,NaN,NaN,NaN,47.478255,3.748127,3.897402,38.005910,NaN,1.482697e+06
std,NaN,NaN,NaN,NaN,6.063410,NaN,NaN,3.851758e+06,NaN,NaN,NaN,NaN,7.493073,0.723096,0.637670,10.110063,NaN,3.851758e+06
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,3.150200e+04,NaN,NaN,NaN,NaN,35.000000,2.500000,2.800000,21.000000,NaN,3.150200e+04
25%,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,8.981650e+04,NaN,NaN,NaN,NaN,41.000000,3.100000,3.300000,29.000000,NaN,8.981650e+04
50%,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,1.355590e+05,NaN,NaN,NaN,NaN,47.000000,3.700000,3.900000,38.000000,NaN,1.355590e+05
75%,NaN,NaN,NaN,NaN,15.000000,NaN,NaN,2.294970e+05,NaN,NaN,NaN,NaN,54.000000,4.400000,4.400000,47.000000,NaN,2.294970e+05
max,NaN,NaN,NaN,NaN,20.000000,NaN,NaN,2.519841e+07,NaN,NaN,NaN,NaN,60.000000,5.000000,5.000000,55.000000,NaN,2.519841e+07

In [9]:
df['salary_lpa'] = df['salary']/100000

In [10]:
df.head()

,job_title,company_size,employment_type,experience_level,years_experience,education_level,country,salary_local_currency,currency,remote_type,primary_skill,secondary_skill,work_hours_per_week,job_satisfaction_score,company_rating,age,gender,salary,salary_lpa
0,DevOps Engineer,SME,Full-time,Entry,3,Self-taught,India,1087489,INR,Onsite,SQL,Java,35,2.7,3.3,22,Female,1087489,10.87489
1,Blockchain Engineer,Mid-size,Full-time,Lead,5,Diploma,France,133007,USD,Hybrid,AWS,React,41,4.9,3.5,26,Prefer not to say,133007,1.33007
2,Cloud Engineer,Startup,Freelance,Senior,14,Self-taught,India,2579715,INR,Onsite,Kubernetes,C++,52,3.2,4.2,44,Female,2579715,25.79715
3,Cybersecurity Analyst,Startup,Full-time,Entry,3,Diploma,India,949111,INR,Hybrid,NoSQL,Docker,40,3.4,3.3,38,Male,949111,9.49111
4,DevOps Engineer,SME,Contract,Mid,12,PhD,Japan,13961380,USD,Remote,PyTorch,GCP,59,4.4,3.3,23,Other,13961380,139.61380

In [11]:
def clean_role(title):
    if 'data analyst' in title:
        return 'data analyst'
    elif 'data scientist' in title:
        return 'data scientist'
    elif 'engineer' in title:
        return 'data engineer'
    else:
        return 'other'

df['job_role_clean'] = df['job_title'].apply(clean_role)

In [12]:
df.head(20)

,job_title,company_size,employment_type,experience_level,years_experience,education_level,country,salary_local_currency,currency,remote_type,primary_skill,secondary_skill,work_hours_per_week,job_satisfaction_score,company_rating,age,gender,salary,salary_lpa,job_role_clean
0,DevOps Engineer,SME,Full-time,Entry,3,Self-taught,India,1087489,INR,Onsite,SQL,Java,35,2.7,3.3,22,Female,1087489,10.87489,other
1,Blockchain Engineer,Mid-size,Full-time,Lead,5,Diploma,France,133007,USD,Hybrid,AWS,React,41,4.9,3.5,26,Prefer not to say,133007,1.33007,other
2,Cloud Engineer,Startup,Freelance,Senior,14,Self-taught,India,2579715,INR,Onsite,Kubernetes,C++,52,3.2,4.2,44,Female,2579715,25.79715,other
3,Cybersecurity Analyst,Startup,Full-time,Entry,3,Diploma,India,949111,INR,Hybrid,NoSQL,Docker,40,3.4,3.3,38,Male,949111,9.49111,other
4,DevOps Engineer,SME,Contract,Mid,12,PhD,Japan,13961380,USD,Remote,PyTorch,GCP,59,4.4,3.3,23,Other,13961380,139.61380,other
5,Full Stack Developer,Mid-size,Full-time,Senior,20,Diploma,Netherlands,89145,USD,Hybrid,NoSQL,React,43,2.8,4.4,55,Other,89145,0.89145,other
6,Product Manager,SME,Full-time,Lead,16,Diploma,Japan,21061490,USD,Onsite,Java,JavaScript,39,4.1,4.5,48,Male,21061490,210.61490,other
7,Blockchain Engineer,Mid-size,Freelance,Lead,0,Bachelor,Netherlands,239587,USD,Remote,AWS,GCP,38,3.2,3.1,21,Other,239587,2.39587,other
8,AI Researcher,Mid-size,Freelance,Mid,16,Self-taught,France,111542,USD,Onsite,React,Docker,59,2.9,4.9,54,Male,111542,1.11542,other
9,Software Engineer,Startup,Contract,Senior,9,Master,Japan,18476420,USD,Onsite,PyTorch,C++,37,4.3,4.6,55,Female,18476420,184.76420,other
10,Frontend Developer,Mid-size,Freelance,Lead,19,Diploma,Germany,228713,USD,Onsite,TensorFlow,Azure,47,5.0,4.2,49,Prefer not to say,228713,2.28713,other
11,ML Engineer,Mid-size,Full-time,Mid,18,Self-taught,India,1342448,INR,Onsite,PyTorch,Python,37,4.3,2.9,25,Male,1342448,13.42448,other
12,DevOps Engineer,Mid-size,Freelance,Entry,15,Master,Australia,92673,USD,Remote,React,Linux,42,4.5,4.6,33,Male,92673,0.92673,other
13,Game Developer,Enterprise,Contract,Lead,1,Bachelor,India,3394855,INR,Onsite,Kubernetes,GCP,60,4.7,3.3,33,Prefer not to say,3394855,33.94855,other
14,Cloud Engineer,Enterprise,Full-time,Lead,2,Diploma,Germany,142290,USD,Remote,JavaScript,Java,55,5.0,4.6,26,Female,142290,1.42290,other
15,Embedded Systems Engineer,SME,Contract,Lead,1,Master,Germany,213575,USD,Hybrid,Python,Kubernetes,43,4.8,4.5,39,Prefer not to say,213575,2.13575,other
16,Full Stack Developer,Mid-size,Full-time,Lead,1,Self-taught,France,117520,USD,Remote,Java,GCP,36,2.6,3.8,54,Female,117520,1.17520,other
17,ML Engineer,Startup,Freelance,Entry,7,Diploma,USA,66049,USD,Onsite,PyTorch,Java,54,2.7,4.2,54,Other,66049,0.66049,other
18,Data Analyst,SME,Contract,Mid,12,Master,Canada,147782,USD,Remote,Azure,NoSQL,45,4.8,4.9,21,Prefer not to say,147782,1.47782,other
19,Full Stack Developer,Mid-size,Full-time,Entry,11,Bachelor,Japan,4360377,USD,Onsite,Docker,Azure,40,3.6,4.0,40,Male,4360377,43.60377,other

In [13]:
def clean_text_column(col):
    return (col.astype(str)
              .str.strip()
              .str.lower()
              .str.replace(r'[^\w\s]', '', regex=True)
              .str.replace(r'\s+', '_', regex=True))

# Apply to all object columns
for col in df.select_dtypes(include='object').columns:
    df[col] = clean_text_column(df[col])

In [14]:
df.head()

,job_title,company_size,employment_type,experience_level,years_experience,education_level,country,salary_local_currency,currency,remote_type,primary_skill,secondary_skill,work_hours_per_week,job_satisfaction_score,company_rating,age,gender,salary,salary_lpa,job_role_clean
0,devops_engineer,sme,fulltime,entry,3,selftaught,india,1087489,inr,onsite,sql,java,35,2.7,3.3,22,female,1087489,10.87489,other
1,blockchain_engineer,midsize,fulltime,lead,5,diploma,france,133007,usd,hybrid,aws,react,41,4.9,3.5,26,prefer_not_to_say,133007,1.33007,other
2,cloud_engineer,startup,freelance,senior,14,selftaught,india,2579715,inr,onsite,kubernetes,c,52,3.2,4.2,44,female,2579715,25.79715,other
3,cybersecurity_analyst,startup,fulltime,entry,3,diploma,india,949111,inr,hybrid,nosql,docker,40,3.4,3.3,38,male,949111,9.49111,other
4,devops_engineer,sme,contract,mid,12,phd,japan,13961380,usd,remote,pytorch,gcp,59,4.4,3.3,23,other,13961380,139.61380,other

In [15]:
def clean_role(title):
    if 'data analyst' in title:
        return 'data analyst'
    elif 'data scientist' in title:
        return 'data scientist'
    elif 'data engineer' in title:
        return 'data engineer'
    else:
        return 'other'

df['job_role_clean'] = df['job_title'].apply(clean_role)

In [16]:
df.head()

,job_title,company_size,employment_type,experience_level,years_experience,education_level,country,salary_local_currency,currency,remote_type,primary_skill,secondary_skill,work_hours_per_week,job_satisfaction_score,company_rating,age,gender,salary,salary_lpa,job_role_clean
0,devops_engineer,sme,fulltime,entry,3,selftaught,india,1087489,inr,onsite,sql,java,35,2.7,3.3,22,female,1087489,10.87489,other
1,blockchain_engineer,midsize,fulltime,lead,5,diploma,france,133007,usd,hybrid,aws,react,41,4.9,3.5,26,prefer_not_to_say,133007,1.33007,other
2,cloud_engineer,startup,freelance,senior,14,selftaught,india,2579715,inr,onsite,kubernetes,c,52,3.2,4.2,44,female,2579715,25.79715,other
3,cybersecurity_analyst,startup,fulltime,entry,3,diploma,india,949111,inr,hybrid,nosql,docker,40,3.4,3.3,38,male,949111,9.49111,other
4,devops_engineer,sme,contract,mid,12,phd,japan,13961380,usd,remote,pytorch,gcp,59,4.4,3.3,23,other,13961380,139.61380,other

In [17]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\sk amir sohayel\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in c:\users\sk amir sohayel\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\sk amir sohayel\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sk amir sohayel\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
from sqlalchemy import create_engine

# replace with your actual credentials
username = "postgres"
password = "2523"
host = "localhost"
port = "5432"
database = "tech_jobs_salaries"

engine = create_engine(f"postgresql://{username}:{password}@{host}:{port}/{database}")

table_name = "tech_jobs"
df.to_sql(table_name, engine, if_exists = "replace" , index = False)

print(f"Data Successfully loaded into table'{table_name}' in database '{database}'.")

Data Successfully loaded into table'tech_jobs' in database 'tech_jobs_salaries'.